### ISSUE TITLE
Koodikatselmointi 1

### ISSUE THREAD

**Issue by Walther** [zirinna/HimmunHedelmaPeli#1]
# Code Review: Himmun Hedelmäpeli
## Plussat
- Pirteät piirrokset! :D
- Hyvä jaottelu paketteihin ja luokkiin
- Hyvät kommentit!
- Testiluokat luotu jokaiselle luokalle
- Varsin hyvä testikattavuus
- Selkeät nimet luokilla, metodeilla, testeillä
## Kehitysehdotukset
- Dependenssiongelma: `package javafx does not exist`. Kerro lisäriippuvuudesta dokumentaatiossa, ja ohjeista asentamaan.
- Main-luokka saattaisi hyötyä refaktoroinnista: ehkä GUI toiseen luokkaan mahdollistaisi "uusi peli?" -promptin?

**Comment by zirinna** [comment]
Tosiaan joo JavaFX:n takia pelini vaatii Java8:n (jossa JavaFX pitäisi olla vakiona mukana), lisäsin tiedon tästä README.hen :)
