### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by dropleton** [zirinna/HimmunHedelmaPeli#2]
Projekti haettu GitHubista 22.04.2016 klo 20:47

Moi!

Heti alkuun minun pitää sanoa, että teen itse samanlaista Tileihin perustuvaa peliä, ja olet tehnyt koko ohjelmastasi aika lailla omaani selkeämmän ja yksinkertaisemman, pisteet tästä! 

Kaikki toiminnallisuus on jaettu vain Mainin ja GameLogicin kesken, eikä GameLogic sisällä (toisin kuin itselläni..) kerrassaan mitään ylimääräistä. Koodia on jaettu mahdollisilta osin useampiin metodeihin, eikä copypastea juurikaan esiinny. Lisäksi olet mielestäni nimennyt metodit osuvasti (drawEverythingille taisin jopa hiukan naurahtaa ^^). Siis CleanCode-periaatteiden mukaista koodia.

Testauksestasi en osaa sanoa paljoakaan, sillä olen itse laiminlyönyt sitä aika pahasti enkä näin ollen tiedä vielä juurikaan, miten JavaFXThreadingRule-testiluokkasi pitäisi toimia. Checkstyle- ja Pit-raportit näyttävät kuitenkin hyvältä ja kaikki testit menivät testejä ajaessani läpi.

Säästin parhaimman lopuksi: peliäsi oli tosi hauska pelata! :D Toimi täysin ilman bugeja ja virhetekstejä, piirtämäsi kuvat olivat huikeita enkä saanut ohjelmaa kaatumaan. Ainut "vika" pelissäsi oli, ettei se lopu ollenkaan: kun peliä on aikansa klikkaillut, huomaa, ettei yksittäisillä klikkauksilla ole sinänsä vaikutusta peliin, kun voittaminen on yhtä epätodennäköistä kuin häviäminen. Mutta tämä nyt menee jo pelien yleisen suunnittelun puolelle, ohjelmasi oli toimiva ja viihdyttävä näinkin! (:

**Comment by zirinna** [comment]
Heip,

Kiva kuulla että koodi vaikutti suht selkeältä :) JavaFXThreadingRule on vaan luokka, jonka testit vaativat toimiakseen, koska pelini käyttää JavaFX:ää (Swingin sijasta). Harmillisesti en ollut vielä ehtinyt puskea perjantaina tekemiäni muutoksia peliin ennen kuin latasit sen, perjantaina nimittäin toteutin peliin mm. siirto- ja pistelaskurit ja nyt peli loppuu, kun 20 siirtoa on kulunut. Ei enää loputonta klikkailua! :D
